apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - linux-ubuntu-vm.yaml
  - web-server.yaml
  - esx-ntp-config.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/className
        value: best-effort-xsmall
    target:
      kind: VirtualMachine
      name: linux-vm
